server.port=8083
spring.application.name=appointment-service

# Kết nối PostgreSQL (Cần tạo sẵn DB appointment_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/appointment_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Circuit Breaker config
resilience4j.circuitbreaker.instances.doctorServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.doctorServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.doctorServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.doctorServiceCB.permitted-number-of-calls-in-half-open-state=3
logging.level.io.github.resilience4j=DEBUG

# Retry config
resilience4j.retry.instances.patientRetry.max-attempts=3
resilience4j.retry.instances.patientRetry.wait-duration=2s
resilience4j.retry.instances.patientRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

resilience4j.retry.instances.doctorRetry.max-attempts=3
resilience4j.retry.instances.doctorRetry.wait-duration=2s
resilience4j.retry.instances.doctorRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException,org.springframework.web.client.HttpServerErrorException,java.lang.Exception

# Rate Limiter config
resilience4j.ratelimiter.instances.doctorRateLimiter.limit-for-period=10
resilience4j.ratelimiter.instances.doctorRateLimiter.limit-refresh-period=10s
resilience4j.ratelimiter.instances.doctorRateLimiter.timeout-duration=0

# TimeLimiter config
resilience4j.timelimiter.instances.insuranceTimeout.timeout-duration=1s

# Aspect Order (RateLimiter -> CircuitBreaker -> Retry)
resilience4j.ratelimiter.ratelimiter-aspect-order=1
resilience4j.circuitbreaker.circuitbreaker-aspect-order=2
resilience4j.retry.retry-aspect-order=3
