server.port=8888
spring.application.name=config-server
spring.cloud.config.server.git.uri=file:///C:/cungh/rikkei/module-4/session9/pharmacy-config-repo
spring.cloud.config.server.git.default-label=main

encrypt.key=MEDICAL_KEY_SECRET_2026
