server.port=8761
spring.application.name=medical-discovery-server

# Server không tự đăng ký chính mình
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Tắt self-preservation để Server cập nhật trạng thái các service nhanh hơn
eureka.server.enable-self-preservation=false
